const dietTypes = [
  { label: "Gluten Free", value: "Gluten Free" },
  { label: "Vegan", value: "Vegan" },
  { label: "Vegetarian", value: "Vegetarian" },
  { label: "Ketogenic", value: "Ketogenic" },
  { label: "Lacto-Vegetarian", value: "Lacto-Vegetarian" },
  { label: "Ovo-Vegetarian", value: "Ovo-Vegetarian" },
  { label: "Pescetarian", value: "Pescetarian" },
  { label: "Paleo", value: "Paleo" },
  { label: "Primal", value: "Primal" },
  { label: "Super30", value: "Super30" },
  { label: "Low FODMAP", value: "Low FODMAP" },
];

const cuisinces = [
  { label: "American", value: "American" },
  { label: "British", value: "British" },
  { label: "Cajun", value: "Cajun" },
  { label: "Caribbean", value: "Caribbean" },
  { label: "Chinese", value: "Chinese" },
  { label: "Eastern European", value: "Eastern European" },
  { label: "European", value: "European" },
  { label: "French", value: "French" },
  { label: "German", value: "German" },
  { label: "Greek", value: "Greek" },
  { label: "Indian", value: "Indian" },
  { label: "Irish", value: "Irish" },
  { label: "Italian", value: "Italian" },
  { label: "Japanese", value: "Japanese" },
  { label: "Jewish", value: "Jewish" },
  { label: "Korean", value: "Korean" },
  { label: "Latin American", value: "Latin American" },
  { label: "Mediterranean", value: "Mediterranean" },
  { label: "Mexican", value: "Mexican" },
  { label: "Middle Eastern", value: "Middle Eastern" },
  { label: "Nordic", value: "Nordic" },
  { label: "Southern", value: "Southern" },
  { label: "Spanish", value: "Spanish" },
  { label: "Thai", value: "Thai" },
  { label: "Vietnamese", value: "Vietnamese" },
  { label: "African", value: "African" },
  { label: "Asian", value: "Asian" },
];

export default { cuisinces, dietTypes };
