export const Sample = {
  results: [
    {
      id: 715415,
      title: "Red Lentil Soup with Chicken and Turnips",
      image: "https://img.spoonacular.com/recipes/715415-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 716406,
      title: "Asparagus and Pea Soup: Real Convenience Food",
      image: "https://img.spoonacular.com/recipes/716406-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 644387,
      title: "Garlicky Kale",
      image: "https://img.spoonacular.com/recipes/644387-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 715446,
      title: "Slow Cooker Beef Stew",
      image: "https://img.spoonacular.com/recipes/715446-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 782601,
      title: "Red Kidney Bean Jambalaya",
      image: "https://img.spoonacular.com/recipes/782601-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 716426,
      title: "Cauliflower, Brown Rice, and Vegetable Fried Rice",
      image: "https://img.spoonacular.com/recipes/716426-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 716004,
      title:
        "Quinoa and Chickpea Salad with Sun-Dried Tomatoes and Dried Cherries",
      image: "https://img.spoonacular.com/recipes/716004-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 716627,
      title: "Easy Homemade Rice and Beans",
      image: "https://img.spoonacular.com/recipes/716627-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 664147,
      title: "Tuscan White Bean Soup with Olive Oil and Rosemary",
      image: "https://img.spoonacular.com/recipes/664147-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 640941,
      title: "Crunchy Brussels Sprouts Side Dish",
      image: "https://img.spoonacular.com/recipes/640941-312x231.jpg",
      imageType: "jpg",
    },
  ],
  offset: 0,
  number: 10,
  totalResults: 5230,
};

export const Random = {
  recipes: [
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 6,
      gaps: "no",
      preparationMinutes: null,
      cookingMinutes: null,
      aggregateLikes: 14,
      healthScore: 2,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 32.72,
      extendedIngredients: [
        {
          id: 20081,
          aisle: "Baking",
          image: "flour.png",
          consistency: "SOLID",
          name: "all purpose flour",
          nameClean: "wheat flour",
          original: "2 cups all purpose flour",
          originalName: "all purpose flour",
          amount: 2,
          unit: "cups",
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 250,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 20080,
          aisle: "Baking",
          image: "flour.png",
          consistency: "SOLID",
          name: "flour",
          nameClean: "whole wheat flour",
          original: "¼ cup whole wheat flour",
          originalName: "whole wheat flour",
          amount: 0.25,
          unit: "cup",
          meta: ["whole wheat"],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 30,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 18372,
          aisle: "Baking",
          image: "white-powder.jpg",
          consistency: "SOLID",
          name: "baking soda",
          nameClean: "baking soda",
          original: "1 tsp baking soda",
          originalName: "baking soda",
          amount: 1,
          unit: "tsp",
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
            metric: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
          },
        },
        {
          id: 2047,
          aisle: "Spices and Seasonings",
          image: "salt.jpg",
          consistency: "SOLID",
          name: "salt",
          nameClean: "table salt",
          original: "¼ tsp. salt",
          originalName: "salt",
          amount: 0.25,
          unit: "tsp",
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 2021,
          aisle: "Spices and Seasonings",
          image: "ginger.png",
          consistency: "SOLID",
          name: "ground ginger",
          nameClean: "ginger powder",
          original: "1 ½ tsp. ground ginger",
          originalName: "ground ginger",
          amount: 1.5,
          unit: "tsp",
          meta: [],
          measures: {
            us: {
              amount: 1.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 1.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 2010,
          aisle: "Spices and Seasonings",
          image: "cinnamon.jpg",
          consistency: "SOLID",
          name: "cinnamon",
          nameClean: "cinnamon",
          original: "2 tsp. cinnamon",
          originalName: "cinnamon",
          amount: 2,
          unit: "tsp",
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 2,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 2011,
          aisle: "Spices and Seasonings",
          image: "cloves.jpg",
          consistency: "SOLID",
          name: "ground cloves",
          nameClean: "ground clove",
          original: "¼ tsp. ground cloves",
          originalName: "ground cloves",
          amount: 0.25,
          unit: "tsp",
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 1002030,
          aisle: "Spices and Seasonings",
          image: "pepper.jpg",
          consistency: "SOLID",
          name: "pepper",
          nameClean: "black pepper",
          original: "½ tsp. black pepper",
          originalName: "black pepper",
          amount: 0.5,
          unit: "tsp",
          meta: ["black"],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 2025,
          aisle: "Spices and Seasonings",
          image: "ground-nutmeg.jpg",
          consistency: "SOLID",
          name: "ground nutmeg",
          nameClean: "nutmeg",
          original: "½ tsp. fresh ground nutmeg",
          originalName: "fresh ground nutmeg",
          amount: 0.5,
          unit: "tsp",
          meta: ["fresh"],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 1022001,
          aisle: "Spices and Seasonings",
          image: "allspice-ground.jpg",
          consistency: "SOLID",
          name: "ground allspice",
          nameClean: "ground allspice",
          original: "¼ tsp. ground allspice",
          originalName: "ground allspice",
          amount: 0.25,
          unit: "tsp",
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 10019334,
          aisle: "Baking",
          image: "dark-brown-sugar.png",
          consistency: "SOLID",
          name: "brown sugar",
          nameClean: "dark brown sugar",
          original: "1 cup dark brown sugar",
          originalName: "dark brown sugar",
          amount: 1,
          unit: "cup",
          meta: ["dark"],
          measures: {
            us: {
              amount: 1,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 220,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 19304,
          aisle: "Baking",
          image: "molasses.jpg",
          consistency: "SOLID",
          name: "blackstrap molasses",
          nameClean: "molasses",
          original: "1/3 cup blackstrap molasses",
          originalName: "blackstrap molasses",
          amount: 0.33333334,
          unit: "cup",
          meta: [],
          measures: {
            us: {
              amount: 0.33333334,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 112.333,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 9019,
          aisle: "Canned and Jarred",
          image: "applesauce.png",
          consistency: "SOLID",
          name: "apple sauce",
          nameClean: "applesauce",
          original: "¼ cup apple sauce",
          originalName: "apple sauce",
          amount: 0.25,
          unit: "cup",
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 61,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 2050,
          aisle: "Baking",
          image: "vanilla-extract.jpg",
          consistency: "LIQUID",
          name: "vanilla extract",
          nameClean: "vanilla extract",
          original: "1 tsp. vanilla extract",
          originalName: "vanilla extract",
          amount: 1,
          unit: "tsp",
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
            metric: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
          },
        },
        {
          id: 12111111,
          aisle: "Baking",
          image: "vanilla-extract.jpg",
          consistency: "LIQUID",
          name: "maple extract",
          nameClean: "maple extract",
          original: "¼ tsp. maple extract",
          originalName: "maple extract",
          amount: 0.25,
          unit: "tsp",
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 10314355,
          aisle: "Tea and Coffee",
          image: "tea-bags.jpg",
          consistency: "SOLID",
          name: "chai concentrate",
          nameClean: "chai",
          original: "1 Tbsp. chai concentrate (optional)",
          originalName: "chai concentrate (optional)",
          amount: 1,
          unit: "Tbsp",
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: "Tbsp",
              unitLong: "Tbsp",
            },
            metric: {
              amount: 1,
              unitShort: "Tbsp",
              unitLong: "Tbsp",
            },
          },
        },
        {
          id: 1124,
          aisle: "Milk, Eggs, Other Dairy",
          image: "egg-white.jpg",
          consistency: "SOLID",
          name: "egg whites",
          nameClean: "egg whites",
          original: "2 large egg whites",
          originalName: "egg whites",
          amount: 2,
          unit: "large",
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: "large",
              unitLong: "larges",
            },
            metric: {
              amount: 2,
              unitShort: "large",
              unitLong: "larges",
            },
          },
        },
        {
          id: 93751,
          aisle: "Produce",
          image: "candied-ginger-or-crystallized-ginger.jpg",
          consistency: "SOLID",
          name: "candied ginger",
          nameClean: "candied ginger",
          original: "½ cup candied ginger",
          originalName: "candied ginger",
          amount: 0.5,
          unit: "cup",
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 70,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 10719335,
          aisle: "Baking",
          image: "sugar-in-bowl.png",
          consistency: "SOLID",
          name: "granulated sugar",
          nameClean: "granulated sugar",
          original: "½ cup granulated sugar (for coating)",
          originalName: "granulated sugar (for coating)",
          amount: 0.5,
          unit: "cup",
          meta: ["(for coating)"],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 100,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 2010,
          aisle: "Spices and Seasonings",
          image: "cinnamon.jpg",
          consistency: "SOLID",
          name: "cinnamon",
          nameClean: "cinnamon",
          original: "1 tsp. cinnamon (for coating)",
          originalName: "cinnamon (for coating)",
          amount: 1,
          unit: "tsp",
          meta: ["(for coating)"],
          measures: {
            us: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
            metric: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
          },
        },
      ],
      id: 642620,
      title: "Fat Free Gingerbread Cookies",
      readyInMinutes: 45,
      servings: 20,
      sourceUrl:
        "https://www.foodista.com/recipe/HSKYCYMF/fat-free-gingerbread-cookies",
      image: "https://img.spoonacular.com/recipes/642620-556x370.jpg",
      imageType: "jpg",
      summary:
        'Need a \u003Cb\u003Edairy free and lacto ovo vegetarian dessert\u003C/b\u003E? Fat Free Gingerbread Cookies could be a great recipe to try. One portion of this dish contains around \u003Cb\u003E2g of protein\u003C/b\u003E, \u003Cb\u003E0g of fat\u003C/b\u003E, and a total of \u003Cb\u003E145 calories\u003C/b\u003E. This recipe serves 20 and costs 33 cents per serving. If you have candied ginger, brown sugar, ground cloves, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about \u003Cb\u003E45 minutes\u003C/b\u003E. It can be enjoyed any time, but it is especially good for \u003Cb\u003EChristmas\u003C/b\u003E. 14 people found this recipe to be tasty and satisfying. It is brought to you by Foodista. With a spoonacular \u003Cb\u003Escore of 30%\u003C/b\u003E, this dish is rather bad. Similar recipes include \u003Ca href="https://spoonacular.com/recipes/low-fat-gingerbread-men-cookies-kids-can-cook-toosday-495997"\u003ELow Fat Gingerbread Men Cookies {Kids Can Cook Toosday}\u003C/a\u003E, \u003Ca href="https://spoonacular.com/recipes/sugar-free-grain-free-soft-gingerbread-cookies-622689"\u003ESugar Free Grain Free Soft Gingerbread Cookies\u003C/a\u003E, and \u003Ca href="https://spoonacular.com/recipes/healthy-gluten-free-lemon-sugar-cookies-made-sugar-free-low-fat-605962"\u003EHealthy Gluten Free Lemon Sugar Cookies (made sugar free & low fat)\u003C/a\u003E.',
      cuisines: [],
      dishTypes: ["dessert"],
      diets: ["dairy free", "lacto ovo vegetarian"],
      occasions: ["christmas"],
      instructions:
        "Sift together flour, baking soda, salt and spices. Set aside.\nIn a large bowl combine brown sugar, molasses, apple sauce, vanilla extract, maple extract, chai concentrate. Beat with an electric mixer for about four minutes, until smooth. Add egg whites and beat for another minute until well combined.\nSlowly whisk in dry ingredients and beat until completely incorporated. Stir in candied ginger. Chill dough for at least one hour. (I chilled mine overnight)\nPreheat oven to 350.  Line a cookie sheet with parchment paper, or grease with cooking spray.\nCombine granulated sugar with cinnamon in a shallow bowl. Scoop one tablespoon of cookie dough and place in the shallow bowl. Using your hands, coat the dough with the cinnamon sugar and shape into balls.\nPlace cookie dough on prepared cookie sheet leaving about 3 inches between each cookie. Bake for 10-12 minutes.\nRemove from oven and transfer to a rack to cool.\nMakes about 20 cookies.",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Sift together flour, baking soda, salt and spices. Set aside.",
              ingredients: [
                {
                  id: 18372,
                  name: "baking soda",
                  localizedName: "baking soda",
                  image: "white-powder.jpg",
                },
                {
                  id: 2035,
                  name: "spices",
                  localizedName: "spices",
                  image: "spices.png",
                },
                {
                  id: 20081,
                  name: "all purpose flour",
                  localizedName: "all purpose flour",
                  image: "flour.png",
                },
                {
                  id: 2047,
                  name: "salt",
                  localizedName: "salt",
                  image: "salt.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 2,
              step: "In a large bowl combine brown sugar, molasses, apple sauce, vanilla extract, maple extract, chai concentrate. Beat with an electric mixer for about four minutes, until smooth.",
              ingredients: [
                {
                  id: 2050,
                  name: "vanilla extract",
                  localizedName: "vanilla extract",
                  image: "vanilla-extract.jpg",
                },
                {
                  id: 12111111,
                  name: "maple extract",
                  localizedName: "maple extract",
                  image: "vanilla-extract.jpg",
                },
                {
                  id: 9019,
                  name: "applesauce",
                  localizedName: "applesauce",
                  image: "applesauce.png",
                },
                {
                  id: 19334,
                  name: "brown sugar",
                  localizedName: "brown sugar",
                  image: "dark-brown-sugar.png",
                },
                {
                  id: 19304,
                  name: "molasses",
                  localizedName: "molasses",
                  image: "molasses.jpg",
                },
                {
                  id: 10314355,
                  name: "chai",
                  localizedName: "chai",
                  image: "tea-bags.jpg",
                },
              ],
              equipment: [
                {
                  id: 404628,
                  name: "hand mixer",
                  localizedName: "hand mixer",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/hand-mixer.png",
                },
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
                },
              ],
              length: {
                number: 4,
                unit: "minutes",
              },
            },
            {
              number: 3,
              step: "Add egg whites and beat for another minute until well combined.",
              ingredients: [
                {
                  id: 1124,
                  name: "egg whites",
                  localizedName: "egg whites",
                  image: "egg-white.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step: "Slowly whisk in dry ingredients and beat until completely incorporated. Stir in candied ginger. Chill dough for at least one hour. (I chilled mine overnight)",
              ingredients: [
                {
                  id: 93751,
                  name: "candied ginger",
                  localizedName: "candied ginger",
                  image: "candied-ginger-or-crystallized-ginger.jpg",
                },
                {
                  id: 0,
                  name: "dough",
                  localizedName: "dough",
                  image: "pizza-dough",
                },
              ],
              equipment: [
                {
                  id: 404661,
                  name: "whisk",
                  localizedName: "whisk",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
                },
              ],
              length: {
                number: 60,
                unit: "minutes",
              },
            },
            {
              number: 5,
              step: "Preheat oven to 35",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
                },
              ],
            },
            {
              number: 6,
              step: "Line a cookie sheet with parchment paper, or grease with cooking spray.",
              ingredients: [
                {
                  id: 4679,
                  name: "cooking spray",
                  localizedName: "cooking spray",
                  image: "cooking-spray.png",
                },
                {
                  id: 10118192,
                  name: "cookies",
                  localizedName: "cookies",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/shortbread-cookies.jpg",
                },
              ],
              equipment: [
                {
                  id: 404770,
                  name: "baking paper",
                  localizedName: "baking paper",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/baking-paper.jpg",
                },
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/baking-sheet.jpg",
                },
              ],
            },
            {
              number: 7,
              step: "Combine granulated sugar with cinnamon in a shallow bowl. Scoop one tablespoon of cookie dough and place in the shallow bowl. Using your hands, coat the dough with the cinnamon sugar and shape into balls.",
              ingredients: [
                {
                  id: 10719335,
                  name: "granulated sugar",
                  localizedName: "granulated sugar",
                  image: "sugar-in-bowl.png",
                },
                {
                  id: 10219335,
                  name: "cinnamon sugar",
                  localizedName: "cinnamon sugar",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/cinnamon-sugar.png",
                },
                {
                  id: 0,
                  name: "cookie dough",
                  localizedName: "cookie dough",
                  image: "",
                },
                {
                  id: 2010,
                  name: "cinnamon",
                  localizedName: "cinnamon",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
                },
                {
                  id: 0,
                  name: "dough",
                  localizedName: "dough",
                  image: "pizza-dough",
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
                },
              ],
            },
            {
              number: 8,
              step: "Place cookie dough on prepared cookie sheet leaving about 3 inches between each cookie.",
              ingredients: [
                {
                  id: 0,
                  name: "cookie dough",
                  localizedName: "cookie dough",
                  image: "",
                },
                {
                  id: 10118192,
                  name: "cookies",
                  localizedName: "cookies",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/shortbread-cookies.jpg",
                },
              ],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/baking-sheet.jpg",
                },
              ],
            },
            {
              number: 9,
              step: "Bake for 10-12 minutes.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
                },
              ],
              length: {
                number: 12,
                unit: "minutes",
              },
            },
            {
              number: 10,
              step: "Remove from oven and transfer to a rack to cool.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
                },
              ],
            },
            {
              number: 11,
              step: "Makes about 20 cookies.",
              ingredients: [
                {
                  id: 10118192,
                  name: "cookies",
                  localizedName: "cookies",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/shortbread-cookies.jpg",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularScore: 38.3110618591309,
      spoonacularSourceUrl:
        "https://spoonacular.com/fat-free-gingerbread-cookies-642620",
    },
    {
      vegetarian: true,
      vegan: true,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 6,
      gaps: "no",
      preparationMinutes: null,
      cookingMinutes: null,
      aggregateLikes: 2,
      healthScore: 6,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 41.27,
      extendedIngredients: [
        {
          id: 11080,
          aisle: "Produce",
          image: "beets.jpg",
          consistency: "SOLID",
          name: "roasted beets",
          nameClean: "red beet",
          original: "1 medium roasted red beets",
          originalName: "roasted red beets",
          amount: 1,
          unit: "medium",
          meta: ["red"],
          measures: {
            us: {
              amount: 1,
              unitShort: "medium",
              unitLong: "medium",
            },
            metric: {
              amount: 1,
              unitShort: "medium",
              unitLong: "medium",
            },
          },
        },
        {
          id: 16057,
          aisle: "Ethnic Foods",
          image: "chickpeas.png",
          consistency: "SOLID",
          name: "chickpeas",
          nameClean: "chickpeas",
          original: "1 cup cooked chickpeas",
          originalName: "cooked chickpeas",
          amount: 1,
          unit: "cup",
          meta: ["cooked"],
          measures: {
            us: {
              amount: 1,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 164,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 11215,
          aisle: "Produce",
          image: "garlic.png",
          consistency: "SOLID",
          name: "garlic",
          nameClean: "garlic",
          original: "2 cloves garlic, minced",
          originalName: "garlic, minced",
          amount: 2,
          unit: "cloves",
          meta: ["minced"],
          measures: {
            us: {
              amount: 2,
              unitShort: "cloves",
              unitLong: "cloves",
            },
            metric: {
              amount: 2,
              unitShort: "cloves",
              unitLong: "cloves",
            },
          },
        },
        {
          id: 1012014,
          aisle: "Spices and Seasonings",
          image: "ground-cumin.jpg",
          consistency: "SOLID",
          name: "ground cumin",
          nameClean: "ground cumin",
          original: "1 teaspoon ground cumin",
          originalName: "ground cumin",
          amount: 1,
          unit: "teaspoon",
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
            metric: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
          },
        },
        {
          id: 9152,
          aisle: "Produce",
          image: "lemon-juice.jpg",
          consistency: "LIQUID",
          name: "juice of lemon",
          nameClean: "lemon juice",
          original: "juice and zest of 1 lemon",
          originalName: "juice and zest of lemon",
          amount: 1,
          unit: "",
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 1,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 4053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "olive-oil.jpg",
          consistency: "LIQUID",
          name: "olive oil",
          nameClean: "olive oil",
          original: "Olive Oil",
          originalName: "Olive Oil",
          amount: 10,
          unit: "servings",
          meta: [],
          measures: {
            us: {
              amount: 10,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 10,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
        {
          id: 2047,
          aisle: "Spices and Seasonings",
          image: "salt.jpg",
          consistency: "SOLID",
          name: "salt",
          nameClean: "table salt",
          original: "Salt",
          originalName: "Salt",
          amount: 10,
          unit: "servings",
          meta: [],
          measures: {
            us: {
              amount: 10,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 10,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
        {
          id: 12698,
          aisle: "Health Foods",
          image: "tahini-paste.png",
          consistency: "SOLID",
          name: "tahini sesame seed paste",
          nameClean: "tahini",
          original: "1/4 cup tahini sesame seed paste",
          originalName: "tahini sesame seed paste",
          amount: 0.25,
          unit: "cup",
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 60,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
      ],
      id: 658503,
      title: "Roasted Beet Hummus",
      readyInMinutes: 45,
      servings: 10,
      sourceUrl: "https://www.foodista.com/recipe/8JHF7S2G/roasted-beet-hummus",
      image: "https://img.spoonacular.com/recipes/658503-556x370.jpg",
      imageType: "jpg",
      summary:
        'Roasted Beet Hummus requires roughly \u003Cb\u003E45 minutes\u003C/b\u003E from start to finish. This recipe serves 10. This hor d\'oeuvre has \u003Cb\u003E196 calories\u003C/b\u003E, \u003Cb\u003E3g of protein\u003C/b\u003E, and \u003Cb\u003E18g of fat\u003C/b\u003E per serving. For \u003Cb\u003E41 cents per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 5%\u003C/b\u003E of your daily requirements of vitamins and minerals. This recipe is typical of middl eastern cuisine. It is a good option if you\'re following a \u003Cb\u003Egluten free, dairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E diet. It is brought to you by Foodista. 2 people were glad they tried this recipe. Head to the store and pick up tahini sesame seed paste, juice of lemon, salt, and a few other things to make it today. Taking all factors into account, this recipe \u003Cb\u003Eearns a spoonacular score of 41%\u003C/b\u003E, which is solid. Similar recipes include \u003Ca href="https://spoonacular.com/recipes/roasted-beet-hummus-480915"\u003ERoasted Beet Hummus\u003C/a\u003E, \u003Ca href="https://spoonacular.com/recipes/roasted-beet-hummus-510223"\u003ERoasted Beet Hummus\u003C/a\u003E, and \u003Ca href="https://spoonacular.com/recipes/roasted-beet-hummus-1281717"\u003ERoasted Beet Hummus\u003C/a\u003E.',
      cuisines: ["Middle Eastern"],
      dishTypes: [
        "antipasti",
        "condiment",
        "starter",
        "snack",
        "appetizer",
        "dip",
        "antipasto",
        "hor d'oeuvre",
        "spread",
      ],
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
      occasions: [],
      instructions:
        "\u003Col\u003E\u003Cli\u003EPlace all ingredients except for the chickpeas and olive oil in a food processor or blender.\u003C/li\u003E\u003Cli\u003EPulse until well blended.\u003C/li\u003E\u003Cli\u003EAdd the chickpeas and olive oil and pulse until just incorporated.\u003C/li\u003E\u003Cli\u003EAdd more olive oil as necessary for blending the chickpeas into a paste, or to thin out the hummus to a thinner consistency.\u003C/li\u003E\u003Cli\u003EServe with warm pita or flat bread.\u003C/li\u003E\u003C/ol\u003E",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Place all ingredients except for the chickpeas and olive oil in a food processor or blender.Pulse until well blended.",
              ingredients: [
                {
                  id: 16057,
                  name: "chickpeas",
                  localizedName: "chickpeas",
                  image: "chickpeas.png",
                },
                {
                  id: 4053,
                  name: "olive oil",
                  localizedName: "olive oil",
                  image: "olive-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 404771,
                  name: "food processor",
                  localizedName: "food processor",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/food-processor.png",
                },
                {
                  id: 404726,
                  name: "blender",
                  localizedName: "blender",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/blender.png",
                },
              ],
            },
            {
              number: 2,
              step: "Add the chickpeas and olive oil and pulse until just incorporated.",
              ingredients: [
                {
                  id: 16057,
                  name: "chickpeas",
                  localizedName: "chickpeas",
                  image: "chickpeas.png",
                },
                {
                  id: 4053,
                  name: "olive oil",
                  localizedName: "olive oil",
                  image: "olive-oil.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: "Add more olive oil as necessary for blending the chickpeas into a paste, or to thin out the hummus to a thinner consistency.",
              ingredients: [
                {
                  id: 16057,
                  name: "chickpeas",
                  localizedName: "chickpeas",
                  image: "chickpeas.png",
                },
                {
                  id: 4053,
                  name: "olive oil",
                  localizedName: "olive oil",
                  image: "olive-oil.jpg",
                },
                {
                  id: 16158,
                  name: "hummus",
                  localizedName: "hummus",
                  image: "hummus.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step: "Serve with warm pita or flat bread.",
              ingredients: [
                {
                  id: 10018413,
                  name: "flatbread",
                  localizedName: "flatbread",
                  image: "pita-bread.jpg",
                },
                {
                  id: 18413,
                  name: "pita",
                  localizedName: "pita",
                  image: "pita-bread.jpg",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularScore: 47.8151588439941,
      spoonacularSourceUrl:
        "https://spoonacular.com/roasted-beet-hummus-658503",
    },
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 10,
      gaps: "no",
      preparationMinutes: null,
      cookingMinutes: null,
      aggregateLikes: 37,
      healthScore: 2,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 24.23,
      extendedIngredients: [
        {
          id: 20081,
          aisle: "Baking",
          image: "flour.png",
          consistency: "SOLID",
          name: "flour",
          nameClean: "wheat flour",
          original: "4 cups all-purpose flour",
          originalName: "all-purpose flour",
          amount: 4,
          unit: "cups",
          meta: ["all-purpose"],
          measures: {
            us: {
              amount: 4,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 500,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 10719335,
          aisle: "Baking",
          image: "sugar-in-bowl.png",
          consistency: "SOLID",
          name: "granulated sugar",
          nameClean: "granulated sugar",
          original: "2 cups granulated sugar (divided)",
          originalName: "granulated sugar (divided)",
          amount: 2,
          unit: "cups",
          meta: ["divided", "()"],
          measures: {
            us: {
              amount: 2,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 400,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 14214,
          aisle: "Tea and Coffee",
          image: "instant-coffee-or-instant-espresso.png",
          consistency: "SOLID",
          name: "coffee granules",
          nameClean: "instant coffee",
          original: "3 teaspoons instant coffee granules",
          originalName: "instant coffee granules",
          amount: 3,
          unit: "teaspoons",
          meta: ["instant"],
          measures: {
            us: {
              amount: 3,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 3,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 19165,
          aisle: "Baking",
          image: "cocoa-powder.png",
          consistency: "SOLID",
          name: "cocoa",
          nameClean: "cacao powder",
          original: "1 tablespoon cocoa",
          originalName: "cocoa",
          amount: 1,
          unit: "tablespoon",
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: "Tbsp",
              unitLong: "Tbsp",
            },
            metric: {
              amount: 1,
              unitShort: "Tbsp",
              unitLong: "Tbsp",
            },
          },
        },
        {
          id: 18372,
          aisle: "Baking",
          image: "white-powder.jpg",
          consistency: "SOLID",
          name: "baking soda",
          nameClean: "baking soda",
          original: "2 teaspoons baking soda",
          originalName: "baking soda",
          amount: 2,
          unit: "teaspoons",
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 2,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 2047,
          aisle: "Spices and Seasonings",
          image: "salt.jpg",
          consistency: "SOLID",
          name: "salt",
          nameClean: "table salt",
          original: "1 teaspoon salt",
          originalName: "salt",
          amount: 1,
          unit: "teaspoon",
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
            metric: {
              amount: 1,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
          },
        },
        {
          id: 1123,
          aisle: "Milk, Eggs, Other Dairy",
          image: "egg.png",
          consistency: "SOLID",
          name: "eggs",
          nameClean: "egg",
          original: "2 eggs",
          originalName: "eggs",
          amount: 2,
          unit: "",
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 2,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 1230,
          aisle: "Milk, Eggs, Other Dairy",
          image: "buttermilk.jpg",
          consistency: "SOLID",
          name: "buttermilk",
          nameClean: "buttermilk",
          original: "2 cups buttermilk",
          originalName: "buttermilk",
          amount: 2,
          unit: "cups",
          meta: [],
          measures: {
            us: {
              amount: 2,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 480,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1014582,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "vegetable-oil.jpg",
          consistency: "LIQUID",
          name: "canola oil",
          nameClean: "canola oil",
          original: "1/2 cup canola oil",
          originalName: "canola oil",
          amount: 0.5,
          unit: "cup",
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 112,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1012010,
          aisle: "Spices and Seasonings",
          image: "cinnamon.jpg",
          consistency: "SOLID",
          name: "ground cinnamon",
          nameClean: "ground cinnamon",
          original: "3 teaspoons ground cinnamon",
          originalName: "ground cinnamon",
          amount: 3,
          unit: "teaspoons",
          meta: [],
          measures: {
            us: {
              amount: 3,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 3,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 9299,
          aisle: "Baking",
          image: "raisins.jpg",
          consistency: "SOLID",
          name: "optional: raisins",
          nameClean: "raisins",
          original: "Optional: 1/2 cup raisins",
          originalName: "Optional: raisins",
          amount: 0.5,
          unit: "cup",
          meta: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 72.5,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
      ],
      id: 639465,
      title: "Cinnamon Mocha Quick Bread",
      readyInMinutes: 45,
      servings: 16,
      sourceUrl:
        "https://www.foodista.com/recipe/YVJD7FQ4/cinnamon-mocha-quick-bread",
      image: "https://img.spoonacular.com/recipes/639465-556x370.jpg",
      imageType: "jpg",
      summary:
        'Cinnamon Mocha Quick Bread might be a good recipe to expand your breakfast repertoire. One serving contains \u003Cb\u003E265 calories\u003C/b\u003E, \u003Cb\u003E5g of protein\u003C/b\u003E, and \u003Cb\u003E3g of fat\u003C/b\u003E. This recipe serves 16. For \u003Cb\u003E24 cents per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 7%\u003C/b\u003E of your daily requirements of vitamins and minerals. If you have salt, cocoa, baking soda, and a few other ingredients on hand, you can make it. 37 people were impressed by this recipe. It is brought to you by Foodista. From preparation to the plate, this recipe takes around \u003Cb\u003E45 minutes\u003C/b\u003E. It is a good option if you\'re following a \u003Cb\u003Elacto ovo vegetarian\u003C/b\u003E diet. Overall, this recipe earns a \u003Cb\u003Erather bad spoonacular score of 31%\u003C/b\u003E. If you like this recipe, you might also like recipes such as \u003Ca href="https://spoonacular.com/recipes/cinnamon-walnut-quick-bread-499231"\u003ECinnamon-Walnut Quick Bread\u003C/a\u003E, \u003Ca href="https://spoonacular.com/recipes/cinnamon-sugar-quick-bread-1514935"\u003ECinnamon Sugar Quick Bread\u003C/a\u003E, and \u003Ca href="https://spoonacular.com/recipes/cinnamon-roll-quick-bread-618244"\u003ECinnamon Roll Quick Bread\u003C/a\u003E.',
      cuisines: [],
      dishTypes: ["morning meal", "dessert", "brunch", "breakfast"],
      diets: ["lacto ovo vegetarian"],
      occasions: [],
      instructions:
        '1.  In a bowl, combine the flour, 1 1/2 cups sugar, coffee granules, cocoa, baking soda, and salt. In a small bowl, whisk the eggs, buttermilk and oil. Stir into the dry ingredients just until moistened. (Optional -- fold in raisins)\n2.  Transfer a fourth of the batter into each of two greased 8"x4" loaf pans. Combine cinnamon and remaining sugar; sprinkle half over batter in each loaf pan. Repeat layers.\n3.  Cut through batter with a knife to swirl.\n4.   Bake at 350 degrees for 55 to 60 minutes or until a toothpick inserted near the center comes out clean. Cool in pans for 10 minutes; remove from pans to wire racks to cool completely.',
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "In a bowl, combine the flour, 1 1/2 cups sugar, coffee granules, cocoa, baking soda, and salt. In a small bowl, whisk the eggs, buttermilk and oil. Stir into the dry ingredients just until moistened. (Optional -- fold in raisins)",
              ingredients: [
                {
                  id: 14214,
                  name: "instant coffee",
                  localizedName: "instant coffee",
                  image: "instant-coffee-or-instant-espresso.png",
                },
                {
                  id: 18372,
                  name: "baking soda",
                  localizedName: "baking soda",
                  image: "white-powder.jpg",
                },
                {
                  id: 1230,
                  name: "buttermilk",
                  localizedName: "buttermilk",
                  image: "buttermilk.jpg",
                },
                {
                  id: 9299,
                  name: "raisins",
                  localizedName: "raisins",
                  image: "raisins.jpg",
                },
                {
                  id: 19165,
                  name: "cocoa powder",
                  localizedName: "cocoa powder",
                  image: "cocoa-powder.png",
                },
                {
                  id: 20081,
                  name: "all purpose flour",
                  localizedName: "all purpose flour",
                  image: "flour.png",
                },
                {
                  id: 19335,
                  name: "sugar",
                  localizedName: "sugar",
                  image: "sugar-in-bowl.png",
                },
                {
                  id: 1123,
                  name: "egg",
                  localizedName: "egg",
                  image: "egg.png",
                },
                {
                  id: 2047,
                  name: "salt",
                  localizedName: "salt",
                  image: "salt.jpg",
                },
                {
                  id: 4582,
                  name: "cooking oil",
                  localizedName: "cooking oil",
                  image: "vegetable-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 404661,
                  name: "whisk",
                  localizedName: "whisk",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
                },
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
                },
              ],
            },
            {
              number: 2,
              step: 'Transfer a fourth of the batter into each of two greased 8"x4" loaf pans.',
              ingredients: [],
              equipment: [
                {
                  id: 404715,
                  name: "loaf pan",
                  localizedName: "loaf pan",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/loaf-pan.png",
                },
              ],
            },
            {
              number: 3,
              step: "Combine cinnamon and remaining sugar; sprinkle half over batter in each loaf pan. Repeat layers.",
              ingredients: [
                {
                  id: 2010,
                  name: "cinnamon",
                  localizedName: "cinnamon",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
                },
                {
                  id: 19335,
                  name: "sugar",
                  localizedName: "sugar",
                  image: "sugar-in-bowl.png",
                },
              ],
              equipment: [
                {
                  id: 404715,
                  name: "loaf pan",
                  localizedName: "loaf pan",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/loaf-pan.png",
                },
              ],
            },
            {
              number: 4,
              step: "Cut through batter with a knife to swirl.",
              ingredients: [],
              equipment: [
                {
                  id: 404745,
                  name: "knife",
                  localizedName: "knife",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/chefs-knife.jpg",
                },
              ],
            },
            {
              number: 5,
              step: "Bake at 350 degrees for 55 to 60 minutes or until a toothpick inserted near the center comes out clean. Cool in pans for 10 minutes; remove from pans to wire racks to cool completely.",
              ingredients: [],
              equipment: [
                {
                  id: 404644,
                  name: "toothpicks",
                  localizedName: "toothpicks",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/toothpicks.jpg",
                },
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
                },
              ],
              length: {
                number: 65,
                unit: "minutes",
              },
            },
          ],
        },
      ],
      originalId: null,
      spoonacularScore: 40.523307800293,
      spoonacularSourceUrl:
        "https://spoonacular.com/cinnamon-mocha-quick-bread-639465",
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 20,
      gaps: "no",
      preparationMinutes: null,
      cookingMinutes: null,
      aggregateLikes: 76,
      healthScore: 14,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 196.37,
      extendedIngredients: [
        {
          id: 18334,
          aisle: "Refrigerated",
          image: "pie-crust.jpg",
          consistency: "SOLID",
          name: "crust",
          nameClean: "refrigerated pie crust",
          original: "Crust",
          originalName: "Crust",
          amount: 12,
          unit: "servings",
          meta: [],
          measures: {
            us: {
              amount: 12,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 12,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
        {
          id: 12155,
          aisle: "Baking",
          image: "walnuts.jpg",
          consistency: "SOLID",
          name: "walnuts",
          nameClean: "walnuts",
          original: "- 3 cups raw walnuts",
          originalName: "raw walnuts",
          amount: 3,
          unit: "cups",
          meta: ["raw"],
          measures: {
            us: {
              amount: 3,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 351,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 16055,
          aisle: "Health Foods",
          image: "carob-powder.jpg",
          consistency: "SOLID",
          name: "cocoa / carob powder",
          nameClean: "carob powder",
          original: "- 2/3 cup raw cocoa / carob powder",
          originalName: "raw cocoa / carob powder",
          amount: 0.6666667,
          unit: "cup",
          meta: ["raw"],
          measures: {
            us: {
              amount: 0.6666667,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 68.667,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1012047,
          aisle: "Spices and Seasonings",
          image: "salt.jpg",
          consistency: "SOLID",
          name: "sea salt",
          nameClean: "coarse sea salt",
          original: "- a pinch of sea salt",
          originalName: "a of sea salt",
          amount: 1,
          unit: "pinch",
          meta: [],
          measures: {
            us: {
              amount: 1,
              unitShort: "pinch",
              unitLong: "pinch",
            },
            metric: {
              amount: 1,
              unitShort: "pinch",
              unitLong: "pinch",
            },
          },
        },
        {
          id: 9087,
          aisle: "Dried Fruits",
          image: "dates.jpg",
          consistency: "SOLID",
          name: "dates",
          nameClean: "dates",
          original: "- 1 cup dates, pitted",
          originalName: "dates, pitted",
          amount: 1,
          unit: "cup",
          meta: ["pitted"],
          measures: {
            us: {
              amount: 1,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 147,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 19270,
          aisle: "Frozen",
          image: "chocolate-ice-cream.png",
          consistency: "SOLID",
          name: "chocolate cream",
          nameClean: "chocolate ice cream",
          original: "Chocolate cream",
          originalName: "Chocolate cream",
          amount: 12,
          unit: "servings",
          meta: [],
          measures: {
            us: {
              amount: 12,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 12,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
        {
          id: 19296,
          aisle: "Nut butters, Jams, and Honey",
          image: "honey.png",
          consistency: "LIQUID",
          name: "honey",
          nameClean: "honey",
          original: "- 1/4 cup honey (or any other healthy sweetener)",
          originalName: "honey (or any other healthy sweetener)",
          amount: 0.25,
          unit: "cup",
          meta: ["or any other healthy sweetener)"],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 84.75,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 9040,
          aisle: "Produce",
          image: "bananas.jpg",
          consistency: "SOLID",
          name: "bananas",
          nameClean: "banana",
          original: "- 3 bananas, ripe",
          originalName: "bananas, ripe",
          amount: 3,
          unit: "",
          meta: ["ripe"],
          measures: {
            us: {
              amount: 3,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 3,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 19165,
          aisle: "Baking",
          image: "cocoa-powder.png",
          consistency: "SOLID",
          name: "cocoa/carob",
          nameClean: "cacao powder",
          original: "- 1/3 cup cocoa/carob",
          originalName: "cocoa/carob",
          amount: 0.33333334,
          unit: "cup",
          meta: [],
          measures: {
            us: {
              amount: 0.33333334,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 28.667,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 9302,
          aisle: "Produce",
          image: "raspberries.jpg",
          consistency: "SOLID",
          name: "raspberries",
          nameClean: "raspberries",
          original: "- about 1 1/2 cups raspberries",
          originalName: "about raspberries",
          amount: 1.5,
          unit: "cups",
          meta: [],
          measures: {
            us: {
              amount: 1.5,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 180,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 10193645,
          aisle: "Baking",
          image: "chocolate-sprinkles.jpg",
          consistency: "SOLID",
          name: "chocolate flakes)",
          nameClean: "chocolate flakes",
          original: "- 5 tbsp dark chocolate flakes( I used 85% cocoa)",
          originalName: "dark chocolate flakes( I used 85% cocoa)",
          amount: 5,
          unit: "tbsp",
          meta: ["dark", "85%"],
          measures: {
            us: {
              amount: 5,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
            metric: {
              amount: 5,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
          },
        },
      ],
      id: 658007,
      title: "Raw Vegan Chocolate and Raspberry Cake",
      readyInMinutes: 45,
      servings: 12,
      sourceUrl:
        "https://www.foodista.com/recipe/CDSD8KXF/raw-vegan-chocolate-and-raspberry-cake",
      image: "https://img.spoonacular.com/recipes/658007-556x370.jpg",
      imageType: "jpg",
      summary:
        'Raw Vegan Chocolate and Raspberry Cake is a \u003Cb\u003Edairy free\u003C/b\u003E recipe with 12 servings. This dessert has \u003Cb\u003E565 calories\u003C/b\u003E, \u003Cb\u003E10g of protein\u003C/b\u003E, and \u003Cb\u003E33g of fat\u003C/b\u003E per serving. For \u003Cb\u003E$1.96 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 16%\u003C/b\u003E of your daily requirements of vitamins and minerals. 76 people have made this recipe and would make it again. From preparation to the plate, this recipe takes around \u003Cb\u003E45 minutes\u003C/b\u003E. It is brought to you by Foodista. If you have crust, sea salt, cocoa / carob powder, and a few other ingredients on hand, you can make it. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 73%\u003C/b\u003E. This score is pretty good. Try \u003Ca href="https://spoonacular.com/recipes/no-bake-chocolate-fudge-fridge-cake-raw-vegan-paleo-512260"\u003ENo-Bake Chocolate Fudge Fridge Cake (Raw, Vegan, Paleo)\u003C/a\u003E, \u003Ca href="https://spoonacular.com/recipes/raw-vegan-raspberry-cheesecake-1265163"\u003ERaw Vegan Raspberry Cheesecake\u003C/a\u003E, and \u003Ca href="https://spoonacular.com/recipes/raw-vegan-raspberry-cheesecake-1238787"\u003ERaw Vegan Raspberry Cheesecake\u003C/a\u003E for similar recipes.',
      cuisines: [],
      dishTypes: ["dessert"],
      diets: ["dairy free"],
      occasions: [],
      instructions:
        "Go to my blog for the full instructions: http://gourmandelle.com/raw-vegan-chocolate-and-raspberry-birthday-cake/",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Go to my blog for the full instructions: http://gourmandelle.com/raw-vegan-chocolate-and-raspberry-birthday-cake/",
              ingredients: [
                {
                  id: 19081,
                  name: "chocolate",
                  localizedName: "chocolate",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/milk-chocolate.jpg",
                },
                {
                  id: 9302,
                  name: "raspberries",
                  localizedName: "raspberries",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/raspberries.jpg",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularScore: 74.8429336547852,
      spoonacularSourceUrl:
        "https://spoonacular.com/raw-vegan-chocolate-and-raspberry-cake-658007",
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: true,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 32,
      gaps: "no",
      preparationMinutes: 20,
      cookingMinutes: 20,
      aggregateLikes: 32767,
      healthScore: 20,
      creditsText: "Jen West",
      sourceName: "Pink When",
      pricePerServing: 633.3,
      extendedIngredients: [
        {
          id: 10018166,
          aisle: "Sweet Snacks",
          image: "oreos.png",
          consistency: "SOLID",
          name: "oreo cookies 3 cups",
          nameClean: "oreo cookies",
          original: "36 OREO cookies finely crushed about 3 cups",
          originalName: "OREO cookies finely crushed about 3 cups",
          amount: 36,
          unit: "",
          meta: ["crushed", "finely"],
          measures: {
            us: {
              amount: 36,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 36,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 1017,
          aisle: "Cheese",
          image: "cream-cheese.jpg",
          consistency: "SOLID",
          name: "cream cheese",
          nameClean: "cream cheese",
          original: "1 package 8oz. cream cheese (softened)",
          originalName: "8oz. cream cheese (softened)",
          amount: 1,
          unit: "package",
          meta: ["softened", "()"],
          measures: {
            us: {
              amount: 1,
              unitShort: "pkg",
              unitLong: "package",
            },
            metric: {
              amount: 1,
              unitShort: "pkg",
              unitLong: "package",
            },
          },
        },
        {
          id: 19078,
          aisle: "Baking",
          image: "baking-chocolate.jpg",
          consistency: "SOLID",
          name: "semi baking chocolate",
          nameClean: "unsweetened baking chocolate",
          original: "4 4oz. semi sweet baking chocolate (melted)",
          originalName: "semi sweet baking chocolate (melted)",
          amount: 16,
          unit: "oz",
          meta: ["sweet", "melted", "()"],
          measures: {
            us: {
              amount: 16,
              unitShort: "oz",
              unitLong: "ounces",
            },
            metric: {
              amount: 453.592,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 93637,
          aisle: "Sweet Snacks",
          image: "candy-corn.jpg",
          consistency: "SOLID",
          name: "candy corn",
          nameClean: "candy corn",
          original: "***Candy Corn",
          originalName: "Candy Corn",
          amount: 48,
          unit: "servings",
          meta: [],
          measures: {
            us: {
              amount: 48,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 48,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
        {
          id: 10023232,
          aisle: "Meat",
          image: "ribeye-raw.jpg",
          consistency: "SOLID",
          name: "candy eyes",
          nameClean: "ribeye steak",
          original: "***Candy eyes",
          originalName: "Candy eyes",
          amount: 48,
          unit: "servings",
          meta: [],
          measures: {
            us: {
              amount: 48,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 48,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
        {
          id: 10019230,
          aisle: "Baking",
          image: "frosting-or-icing.png",
          consistency: "SOLID",
          name: "icing",
          nameClean: "icing",
          original: "***Icing",
          originalName: "Icing",
          amount: 48,
          unit: "servings",
          meta: [],
          measures: {
            us: {
              amount: 48,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 48,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
      ],
      id: 715449,
      title: "How to Make OREO Turkeys for Thanksgiving",
      readyInMinutes: 40,
      servings: 48,
      sourceUrl:
        "https://www.pinkwhen.com/oreo-cookie-balls-thanksgiving-turkey/",
      image: "https://img.spoonacular.com/recipes/715449-556x370.jpg",
      imageType: "jpg",
      summary:
        'How to Make OREO Turkeys for Thanksgiving requires about \u003Cb\u003E40 minutes\u003C/b\u003E from start to finish. This recipe serves 48. One serving contains \u003Cb\u003E835 calories\u003C/b\u003E, \u003Cb\u003E47g of protein\u003C/b\u003E, and \u003Cb\u003E45g of fat\u003C/b\u003E. For \u003Cb\u003E$6.33 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 27%\u003C/b\u003E of your daily requirements of vitamins and minerals. 32767 people were impressed by this recipe. Head to the store and pick up oreo cookies 3 cups, icing, semi baking chocolate, and a few other things to make it today. It can be enjoyed any time, but it is especially good for \u003Cb\u003EThanksgiving\u003C/b\u003E. It is brought to you by Pink When. Taking all factors into account, this recipe \u003Cb\u003Eearns a spoonacular score of 18%\u003C/b\u003E, which is rather bad. Similar recipes are \u003Ca href="https://spoonacular.com/recipes/how-to-make-oreo-turkeys-for-thanksgiving-1364303"\u003EHow to Make OREO Turkeys for Thanksgiving\u003C/a\u003E, \u003Ca href="https://spoonacular.com/recipes/oreo-turkeys-thanksgiving-snack-138063"\u003EOreo Turkeys (Thanksgiving Snack)\u003C/a\u003E, and \u003Ca href="https://spoonacular.com/recipes/cakespy-thanksgiving-cookie-turkeys-50158"\u003ECakespy: Thanksgiving Cookie Turkeys\u003C/a\u003E.',
      cuisines: [],
      dishTypes: [],
      diets: [],
      occasions: ["thanksgiving"],
      instructions:
        "Instructions\n\nTake a package of OREO cookies and crush them up finely.\n\nTake softened cream cheese and mix well with cookie crumbs.\n\nRoll into one inch cookie balls, and then freeze for 10 minutes.\n\nDip cookie balls into melted chocolate and place on a prepared cookie sheet covered with wax paper.\n\nPlace into the refrigerator for 15 minutes to an hour before decorating.\n\nAdd 5 candy corn to the back of the ball as tail feathers.\n\nUse icing as glue to attach the candy eyes.\n\nCut one candy corn into pieces, using the white tip as the nose, and the orange part (cut in half) as feet.",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Take a package of OREO cookies and crush them up finely.",
              ingredients: [
                {
                  id: 10018166,
                  name: "oreo cookies",
                  localizedName: "oreo cookies",
                  image: "oreos.png",
                },
              ],
              equipment: [],
            },
            {
              number: 2,
              step: "Take softened cream cheese and mix well with cookie crumbs.",
              ingredients: [
                {
                  id: 10018192,
                  name: "cookie crumbs",
                  localizedName: "cookie crumbs",
                  image: "",
                },
                {
                  id: 1017,
                  name: "cream cheese",
                  localizedName: "cream cheese",
                  image: "cream-cheese.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: "Roll into one inch cookie balls, and then freeze for 10 minutes.",
              ingredients: [
                {
                  id: 10118192,
                  name: "cookies",
                  localizedName: "cookies",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/shortbread-cookies.jpg",
                },
                {
                  id: 0,
                  name: "roll",
                  localizedName: "roll",
                  image: "dinner-yeast-rolls.jpg",
                },
              ],
              equipment: [],
              length: {
                number: 10,
                unit: "minutes",
              },
            },
            {
              number: 4,
              step: "Dip cookie balls into melted chocolate and place on a prepared cookie sheet covered with wax paper.",
              ingredients: [
                {
                  id: 19081,
                  name: "chocolate",
                  localizedName: "chocolate",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/milk-chocolate.jpg",
                },
                {
                  id: 10118192,
                  name: "cookies",
                  localizedName: "cookies",
                  image:
                    "https://spoonacular.com/cdn/ingredients_100x100/shortbread-cookies.jpg",
                },
                {
                  id: 0,
                  name: "dip",
                  localizedName: "dip",
                  image: "",
                },
              ],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/baking-sheet.jpg",
                },
                {
                  id: 404739,
                  name: "wax paper",
                  localizedName: "wax paper",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/wax-paper.jpg",
                },
              ],
            },
            {
              number: 5,
              step: "Place into the refrigerator for 15 minutes to an hour before decorating.",
              ingredients: [],
              equipment: [],
              length: {
                number: 15,
                unit: "minutes",
              },
            },
            {
              number: 6,
              step: "Add 5 candy corn to the back of the ball as tail feathers.",
              ingredients: [
                {
                  id: 93637,
                  name: "candy corn",
                  localizedName: "candy corn",
                  image: "candy-corn.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 7,
              step: "Use icing as glue to attach the candy eyes.",
              ingredients: [
                {
                  id: 0,
                  name: "candy",
                  localizedName: "candy",
                  image: "",
                },
                {
                  id: 10019230,
                  name: "icing",
                  localizedName: "icing",
                  image: "frosting-or-icing.png",
                },
              ],
              equipment: [],
            },
            {
              number: 8,
              step: "Cut one candy corn into pieces, using the white tip as the nose, and the orange part (cut in half) as feet.",
              ingredients: [
                {
                  id: 93637,
                  name: "candy corn",
                  localizedName: "candy corn",
                  image: "candy-corn.jpg",
                },
                {
                  id: 9200,
                  name: "orange",
                  localizedName: "orange",
                  image: "orange.png",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularScore: 91.4374389648438,
      spoonacularSourceUrl:
        "https://spoonacular.com/how-to-make-oreo-turkeys-for-thanksgiving-715449",
    },
  ],
};
